# Carrega as integrações padrão. Não remova.
default_config:

# Carrega temas da pasta de temas
frontend:
  themes: !include_dir_merge_named themes

# Inclui automações, scripts e cenas
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Integração CozyLife (componente customizado)
hass_cozylife_local_pull:
  lang: en  # Idioma do componente (ajustável)
  ip:
    - "192.168.15.4"  # IP do dispositivo CozyLife (verifique se está correto)

# Personalização da entidade do Home Assistant
homeassistant:
  customize:
    switch.cozylife_switch:  # Substitua pelo Entity ID correto do seu interruptor CozyLife
      supported_features: 191  # Defina os recursos suportados (ajuste conforme necessário)
